Repository Jenyus-Org/IMSForumPrototype, pull requests merged in 2020-10, with the labels that each got.

#8 Create Interfaces and Models
  Models/Comment.cs
  Models/CommentForest.cs
  Models/Image.cs
  Models/Post.cs
  Models/Submission.cs
  Models/Tag.cs
  Models/Taggable.cs
  Models/Thing.cs
  Models/Tutorial.cs
  Models/User.cs
Labels: enhancement

#11 [ENHANCEMENT] StrAPI and Models
  backend/.editorconfig
  backend/.env.example
  backend/.eslintignore
  backend/.eslintrc
  backend/.gitignore
  backend/README.md
  backend/api/.gitkeep
  backend/api/comment/config/routes.json
  backend/api/comment/controllers/comment.js
  backend/api/comment/models/comment.js
  backend/api/comment/models/comment.settings.json
  backend/api/comment/services/comment.js
  backend/api/post/config/routes.json
  backend/api/post/controllers/post.js
  backend/api/post/models/post.js
  backend/api/post/models/post.settings.json
  backend/api/post/services/post.js
  backend/api/tag/config/routes.json
  backend/api/tag/controllers/tag.js
  backend/api/tag/models/tag.js
  backend/api/tag/models/tag.settings.json
  backend/api/tag/services/tag.js
  backend/api/tutorial/config/routes.json
  backend/api/tutorial/controllers/tutorial.js
  backend/api/tutorial/models/tutorial.js
  backend/api/tutorial/models/tutorial.settings.json
  backend/api/tutorial/services/tutorial.js
  backend/config/database.js
  backend/config/functions/bootstrap.js
  backend/config/functions/cron.js
  backend/config/functions/responses/404.js
  backend/config/server.js
  backend/extensions/.gitkeep
  backend/extensions/users-permissions/config/jwt.js
  backend/extensions/users-permissions/models/User.settings.json
  backend/favicon.ico
  backend/package.json
  backend/public/robots.txt
  backend/public/uploads/.gitkeep
  backend/yarn.lock
Labels: enhancement

#12 [FEATURE] Client SDK with Models and Helpers
  api-sdk/.gitignore
  api-sdk/package.json
  api-sdk/src/baseError.ts
  api-sdk/src/client/client.test.ts
  api-sdk/src/client/client.ts
  api-sdk/src/client/comments.test.ts
  api-sdk/src/client/comments.ts
  api-sdk/src/client/index.ts
  api-sdk/src/client/posts.test.ts
  api-sdk/src/client/posts.ts
  api-sdk/src/client/users.test.ts
  api-sdk/src/client/users.ts
  api-sdk/src/index.ts
  api-sdk/src/models/comment.test.ts
  api-sdk/src/models/comment.ts
  api-sdk/src/models/post.test.ts
  api-sdk/src/models/post.ts
  api-sdk/src/models/submission.ts
  api-sdk/src/models/thing.ts
  api-sdk/src/models/user.ts
  api-sdk/src/strapiErrors.ts
  api-sdk/tsconfig.json
  api-sdk/tslint.json
  backend/api/comment/documentation/1.0.0/comment.json
  backend/api/comment/models/comment.settings.json
  backend/api/post/documentation/1.0.0/post.json
  backend/api/post/models/post.settings.json
  backend/api/tag/documentation/1.0.0/tag.json
  backend/api/tutorial/documentation/1.0.0/tutorial.json
  backend/api/tutorial/models/tutorial.settings.json
  backend/extensions/documentation/documentation/1.0.0/full_documentation.json
  backend/extensions/documentation/public/index.html
  backend/extensions/email/documentation/1.0.0/email-Email.json
  backend/extensions/upload/documentation/1.0.0/upload-File.json
  backend/extensions/users-permissions/documentation/1.0.0/users-permissions-Role.json
  backend/extensions/users-permissions/documentation/1.0.0/users-permissions-User.json
  backend/extensions/users-permissions/models/User.settings.json
  backend/package.json
  backend/yarn.lock
Labels: enhancement

#14 [ENHANCEMENT] Fix API SDK Package Flow
  api-sdk/package.json
  api-sdk/src/client/posts.test.ts
  api-sdk/src/client/posts.ts
  api-sdk/src/models/comment.ts
  api-sdk/src/models/post.ts
  api-sdk/tsconfig.json
Labels: bug

#15 [ENHANCEMENT] Strapi: Update Development Port to 8082
  backend/config/server.js
Labels: enhancement

#13 Issue/9
  client-app/babel.config.js
  client-app/package.json
  client-app/src/App.vue
  client-app/src/assets/css/form.scss
  client-app/src/assets/css/main.css
  client-app/src/assets/css/nav.css
  client-app/src/assets/jenyus-logo.png
  client-app/src/components/Footer.vue
  client-app/src/components/Header.vue
  client-app/src/components/HelloWorld.vue
  client-app/src/components/Navigation.vue
  client-app/src/components/Sidebar.vue
  client-app/src/components/index.js
  client-app/src/main.js
  client-app/src/router/index.js
  client-app/src/store/index.js
  client-app/src/views/General.vue
  client-app/src/views/Home.vue
  client-app/src/views/Settings.vue
  client-app/src/views/SignIn.vue
  client-app/src/views/SignUp.vue
  client-app/yarn.lock
Labels: implementation

#18 [DOCUMENTATION] Client SDK Documentation
  api-sdk/README.md
Labels: documentation

#19 Issue/17 tutorials
  client-app/src/assets/css/main.css
  client-app/src/assets/css/searchbar.scss
  client-app/src/assets/css/tutorial.scss
  client-app/src/components/Footer.vue
  client-app/src/components/Header.vue
  client-app/src/components/Navigation.vue
  client-app/src/components/SearchBar.vue
  client-app/src/components/Sidebar.vue
  client-app/src/components/Tutorial/Card.vue
  client-app/src/main.js
  client-app/src/router/index.js
  client-app/src/views/General.vue
  client-app/src/views/Tutorials.vue
Labels: implementation

#21 Issue/20 tutorial page
  client-app/src/components/Navigation.vue
  client-app/src/components/Tutorial/Card.vue
  client-app/src/main.js
  client-app/src/router/index.js
  client-app/src/views/CreateTutorial.vue
  client-app/src/views/Tutorial.vue
  client-app/src/views/Tutorials.vue
Labels: implementation

#24 [ENHANCEMENTS] Vue Plugin, Usage of Remarkable and Updated Styling
  api-sdk/package.json
  api-sdk/src/helpers/markdown.js
  api-sdk/src/helpers/markdown.test.ts
  api-sdk/src/helpers/markdown.ts
  api-sdk/src/index.ts
  api-sdk/src/models/comment.ts
  api-sdk/src/models/mixins/tocMixin.ts
  api-sdk/src/vuePlugin.d.ts
  api-sdk/src/vuePlugin.ts
  api-sdk/tsconfig.json
  backend/extensions/documentation/documentation/1.0.0/full_documentation.json
  client-app/package.json
  client-app/src/App.vue
  client-app/src/main.js
  client-app/src/plugins/strapi.js
  client-app/src/views/SignIn.vue
  client-app/src/views/SignUp.vue
  client-app/src/views/Tutorial.vue
  client-app/yarn.lock
Labels: enhancement

#29 Implement UserProfile
  backend/extensions/documentation/documentation/1.0.0/full_documentation.json
  client-app/src/components/Footer.vue
  client-app/src/components/Header.vue
  client-app/src/components/Navigation.vue
  client-app/src/components/Sidebar.vue
  client-app/src/main.js
  client-app/src/router/index.js
  client-app/src/views/General.vue
  client-app/src/views/Settings.vue
Labels: implementation

#26 [ENHANCEMENTS] Tutorial Submission Screen, Updated Styles & Highlight.js
  api-sdk/package.json
  api-sdk/src/helpers/markdown.js
  backend/extensions/documentation/documentation/1.0.0/full_documentation.json
  client-app/package.json
  client-app/src/App.vue
  client-app/src/components/Header.vue
  client-app/src/components/SearchBar.vue
  client-app/src/components/Sidebar.vue
  client-app/src/main.js
  client-app/src/router/index.js
  client-app/src/views/CreateTutorial.vue
  client-app/src/views/SubmitTutorial.vue
  client-app/src/views/Tutorial.vue
  client-app/src/views/Tutorials.vue
  client-app/yarn.lock
Labels: enhancement

#34 Implement Tutoring
  client-app/src/components/Navigation.vue
  client-app/src/main.js
  client-app/src/router/index.js
  client-app/src/views/Tutoring.vue
Labels: implementation

#35 [ENHANCEMENTS] Dashboard, Post Detail Overview, Comment Threads, Tutorial Page
  backend/extensions/documentation/documentation/1.0.0/full_documentation.json
  client-app/src/components/Comment.vue
  client-app/src/components/Navigation.vue
  client-app/src/components/Sidebar.vue
  client-app/src/main.js
  client-app/src/router/index.js
  client-app/src/views/Forum.vue
  client-app/src/views/Home.vue
  client-app/src/views/Post.vue
  client-app/src/views/Tutorial.vue
Labels: enhancement

#38 [ENHANCEMENT] User Profile & Updated Styling
  client-app/src/components/Header.vue
  client-app/src/components/Sidebar.vue
Labels: enhancement

#39 [FIX] Usage of Route Objects & Conditional Routes
  client-app/src/App.vue
  client-app/src/components/Header.vue
  client-app/src/components/Layout.vue
  client-app/src/components/Navigation.vue
  client-app/src/components/Tutorial/Card.vue
  client-app/src/router/index.js
  client-app/src/views/Home.vue
  client-app/src/views/Tutorials.vue
  client-app/src/views/User.vue
Labels: bug, enhancement

#40 [ENHANCEMENTS] Header Text Align, Cards and More
  backend/extensions/documentation/documentation/1.0.0/full_documentation.json
  client-app/src/components/Header.vue
  client-app/src/components/Sidebar.vue
  client-app/src/components/SwissMap.vue
  client-app/src/components/Tutorial/Card.vue
  client-app/src/main.js
  client-app/src/utils/filters.js
  client-app/src/views/Forum.vue
  client-app/src/views/Internships.vue
  client-app/src/views/Tutorials.vue
  client-app/src/views/Tutoring.vue
Labels: enhancement
